import {anime,genres,phrases,quiz,onboardingQuestions} from './data.js';
import './styles.css';
const KEY='animePartner.v1';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{onboarded:false,profile:{name:'',age:'',gender:'',experience:''},answers:[],favorites:[],watchlist:[],watching:{},completed:[],notes:[],challenges:[{id:1,title:'Explore 10 anime this month',goal:10,current:2}],settings:{theme:'dark',motion:true,sound:true,notifications:true},page:'home',search:''};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const app=document.querySelector('#app');
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const initials=t=>t.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function toast(msg){let t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.append(t);setTimeout(()=>t.remove(),2300)}
function go(p){state.page=p;state.search='';save();render()}
function find(id){return anime.find(a=>a.id===id)}
function poster(a,large=false){return `<div class="poster ${large?'poster-lg':''}" style="--poster:${a.color||'#7c3aed'}"><span>${initials(a.title)}</span><small>${esc(a.tag||'ANIME')}</small></div>`}
function nav(){return `<nav class="side"><div class="brand" onclick="go('home')"><div class="brandmark">✦</div><div><b>ANIME<br>PARTNER</b><small>watch with your partner</small></div></div><div class="navlinks">${[['home','⌂','Home'],['discover','◈','Discover'],['tracker','✓','My Tracker'],['learn','あ','Learn Japanese'],['quiz','✎','Anime Knowledge'],['games','♟','Game Center'],['match','♡','Anime Match']].map(x=>`<button class="navitem ${state.page===x[0]?'active':''}" onclick="go('${x[0]}')"><i>${x[1]}</i>${x[2]}</button>`).join('')}</div><div class="sidebottom"><button class="navitem" onclick="go('settings')"><i>⚙</i>Settings</button><button class="profile-mini" onclick="go('settings')"><span>${initials(state.profile.name||'You')}</span><b>${esc(state.profile.name||'Your profile')}</b><small>${state.profile.experience||'Guest'}</small></button></div></nav>`}
function topbar(title,sub='') {return `<header class="topbar"><div><div class="eyebrow">ANIME PARTNER / ${title.toUpperCase()}</div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div><div class="top-actions"><button class="iconbtn" onclick="go('search')">⌕</button><button class="avatar" onclick="go('settings')">${initials(state.profile.name||'Y')}</button></div></header>`}
function card(a){let fav=state.favorites.includes(a.id);return `<article class="anime-card" onclick="detail('${a.id}')">${poster(a)}<div class="card-body"><div class="card-title">${esc(a.title)}</div><div class="meta">${a.year||'Year unavailable'} · ${a.type||'Anime'} ${a.rating?`· ★ ${a.rating}`:''}</div><div class="chips">${(a.genres||[]).slice(0,2).map(g=>`<span>${g}</span>`).join('')}</div></div><button class="heart ${fav?'on':''}" onclick="event.stopPropagation();toggleFav('${a.id}')">${fav?'♥':'♡'}</button></article>`}
function shelf(title,list,action='discover'){if(!list.length)return '';return `<section class="shelf"><div class="section-head"><h2>${title}</h2><button class="textbtn" onclick="go('${action}')">See all →</button></div><div class="row-scroll">${list.slice(0,8).map(card).join('')}</div></section>`}
function home(){let rec=recommend();let watching=Object.keys(state.watching).map(find).filter(Boolean);let phrase=phrases[new Date().getDate()%phrases.length];return `${topbar(`Good ${new Date().getHours()<12?'morning':new Date().getHours()<18?'afternoon':'evening'}, ${esc(state.profile.name||'partner')}`,'Your next great story is waiting.')}
<div class="hero"><div><span class="pill violet">✦ PERSONALIZED FOR YOU</span><h2>Your anime journey,<br><em>in one place.</em></h2><p>Discover stories that match your mood, keep your watchlist moving, and learn a little Japanese along the way.</p><button class="primary" onclick="go('discover')">Explore recommendations <span>→</span></button></div><div class="hero-art"><div class="orbit o1"></div><div class="orbit o2"></div><div class="hero-spark">✦</div><div class="hero-card hc1">${poster(anime[0])}</div><div class="hero-card hc2">${poster(anime[8])}</div></div></div>
<div class="quick-grid"><div class="stat-card"><span class="stat-icon">◷</span><div><b>${watching.length}</b><small>Currently watching</small></div><button onclick="go('tracker')">→</button></div><div class="stat-card"><span class="stat-icon gold">★</span><div><b>${state.favorites.length}</b><small>In your favorites</small></div><button onclick="go('discover')">→</button></div><div class="stat-card"><span class="stat-icon mint">火</span><div><b>${state.challenges[0]?.current||0}<small>/${state.challenges[0]?.goal||10}</small></b><small>Challenge progress</small></div><button onclick="go('tracker')">→</button></div></div>
${shelf('Recommended for you',rec)}${shelf(watching.length?'Continue watching':'Popular right now',watching.length?watching:anime.slice(9,17))}<div class="split-grid"><div class="feature-card phrase-card"><div><span class="eyebrow">A LITTLE JAPANESE</span><h3>${phrase[0]}</h3><b>${phrase[1]}</b><p>${phrase[2]}</p></div><button class="circle-btn" onclick="speak('${phrase[0]}')">◖</button></div><div class="feature-card challenge-card"><span class="eyebrow">YOUR NEXT MILESTONE</span><h3>Watch ${Math.max(0,(state.challenges[0]?.goal||10)-(state.challenges[0]?.current||0))} more episodes</h3><div class="progress"><i style="width:${((state.challenges[0]?.current||0)/(state.challenges[0]?.goal||10))*100}%"></i></div><button class="textbtn" onclick="go('tracker')">View challenges →</button></div></div>`}
function recommend(){let liked=state.favorites.map(find).filter(Boolean);let prefs=state.answers||[];return anime.filter(a=>!state.favorites.includes(a.id)).map(a=>{let score=(a.rating||7); score+=(a.genres||[]).filter(g=>prefs.some(p=>p.toLowerCase().includes(g.toLowerCase()))).length*1.7; score+=(a.genres||[]).filter(g=>liked.some(l=>(l.genres||[]).includes(g))).length*2; return {a,score}}).sort((x,y)=>y.score-x.score).map(x=>x.a)}
function discover(){let q=state.search.toLowerCase();let list=anime.filter(a=>!q||[a.title,a.jp,a.studio,...(a.genres||[])].join(' ').toLowerCase().includes(q));return `${topbar('Discover','Find your next favorite, guided by your taste.')}
<div class="searchbar"><span>⌕</span><input value="${esc(state.search)}" oninput="state.search=this.value;render()" placeholder="Search titles, genres, studios..."/><kbd>⌘ K</kbd></div><div class="filter-row"><button class="filter active">All anime</button>${genres.slice(0,8).map(g=>`<button class="filter" onclick="state.search='${g}';render()">${g}</button>`).join('')}</div>${q?`<div class="section-head result-head"><h2>${list.length} results for “${esc(state.search)}”</h2></div>`:`${shelf('Recommended for you',recommend())}<div class="section-head"><h2>Explore the library</h2><span class="subtle">${anime.length}+ titles · local catalog</span></div>`}<div class="card-grid">${list.map(card).join('')}</div>${!list.length?empty('No anime found','Try a different title, genre, or studio.') : ''}`}
function tracker(){let watching=Object.entries(state.watching).map(([id,v])=>({a:find(id),v})).filter(x=>x.a);let completed=state.completed.map(find).filter(Boolean);return `${topbar('My Tracker','Every episode counts. Keep your momentum going.')}
<div class="tracker-hero"><div><span class="eyebrow">YOUR WATCH TIME</span><h2>${(completed.length*8+watching.reduce((n,x)=>n+(x.v||1),0)*.4).toFixed(1)} hours</h2><p>Approximate watch time across your Anime Partner journey.</p></div><div class="ring"><b>${completed.length}</b><small>completed</small></div></div><div class="tabs"><button class="tab active">All activity</button><button class="tab">Watching ${watching.length}</button><button class="tab">Completed ${completed.length}</button><button class="tab">Plan to watch</button></div><div class="tracker-list">${watching.length?watching.map(x=>`<div class="tracker-item">${poster(x.a)}<div class="tracker-info"><h3>${esc(x.a.title)}</h3><p>Episode ${x.v||1} of ${x.a.episodes||'?'} · ${x.a.genres?.slice(0,2).join(' · ')||'Anime'}</p><div class="progress"><i style="width:${x.a.episodes?Math.min(100,(x.v||1)/x.a.episodes*100):18}%"></i></div></div><button class="primary small" onclick="episode('${x.a.id}')">Complete episode</button></div>`).join(''):`${empty('Your tracker is ready','Open an anime and tap Start watching to build your journey.')} `}</div><section class="section-block"><div class="section-head"><h2>Anime Challenges</h2><button class="primary small" onclick="newChallenge()">+ New challenge</button></div><div class="challenge-list">${state.challenges.map(c=>`<div class="challenge"><span class="challenge-icon">✦</span><div><b>${esc(c.title)}</b><p>${c.current} of ${c.goal} complete</p><div class="progress"><i style="width:${Math.min(100,c.current/c.goal*100)}%"></i></div></div><strong>${Math.round(c.current/c.goal*100)}%</strong></div>`).join('')}</div></section>`}
function detail(id){state.detail=id;render()}
function detailPage(a){let fav=state.favorites.includes(a.id);return `<button class="back" onclick="go('discover')">← Back to discover</button><div class="detail-hero"><div class="detail-poster">${poster(a,true)}</div><div class="detail-copy"><span class="pill">${a.tag||'EXPLORE'}</span><h1>${esc(a.title)}</h1><p class="jp">${esc(a.jp||'Japanese title unavailable')}</p><div class="rating">★ ${a.rating||'—'} <span>Community score · ${a.year||'Year unavailable'}</span></div><div class="chips large">${(a.genres?.length?a.genres:['Genre unavailable']).map(g=>`<span>${g}</span>`).join('')}</div><p class="lead">${esc(a.desc||'A full description for this title is not available in the offline catalog yet.')}</p><div class="actions"><button class="primary" onclick="start('${a.id}')">${state.watching[a.id]?'Continue watching':'Start watching'} →</button><button class="outline ${fav?'selected':''}" onclick="toggleFav('${a.id}')">${fav?'♥ Saved':'♡ Favorite'}</button><button class="outline" onclick="shareAnime('${a.title}')">↗ Share</button></div></div></div><div class="detail-facts"><div><small>FORMAT</small><b>${a.type||'Unavailable'}</b></div><div><small>EPISODES</small><b>${a.episodes||'Unavailable'}</b></div><div><small>STATUS</small><b>${a.status||'Unavailable'}</b></div><div><small>STUDIO</small><b>${a.studio||'Unavailable'}</b></div><div><small>DURATION</small><b>${a.duration?`${a.duration} min`:'Unavailable'}</b></div></div><div class="detail-lower"><section><div class="section-head"><h2>Why it may suit you</h2></div><div class="reason"><span>✦</span><p>Recommended because you enjoy <b>${(a.genres||['great stories']).slice(0,2).join(' and ').toLowerCase()}</b>. Your personal recommendations are based on your saved titles and preferences, not certainty.</p></div></section><section><div class="section-head"><h2>Similar picks</h2></div><div class="mini-row">${anime.filter(x=>x.id!==a.id&&x.genres?.some(g=>a.genres?.includes(g))).slice(0,3).map(card).join('')}</div></section></div>`}
function learn(){let p=phrases[state.phraseIndex||0];return `${topbar('Learn Japanese','Small phrases. Real progress. A more immersive watch.') }<div class="learn-hero"><div><span class="pill mint">LESSON 01 · EVERYDAY JAPANESE</span><h2>Say it with confidence.</h2><p>Learn useful expressions you’ll hear again and again, with pronunciation support built right in.</p></div><div class="kana">あ<br><small>kana</small></div></div><div class="lesson-layout"><div class="flashcard"><span class="eyebrow">PHRASE OF THE MOMENT</span><div class="jp-big">${p[0]}</div><h2>${p[1]}</h2><p>${p[2]}</p><small>${p[3]}</small><div class="flash-actions"><button class="outline" onclick="speak('${p[0]}')">◖ Listen</button><button class="primary" onclick="nextPhrase()">I know this →</button></div></div><div class="phrase-list"><div class="section-head"><h2>Phrase library</h2><span class="subtle">${phrases.length} phrases</span></div>${phrases.map((x,i)=>`<button class="phrase-item ${i===(state.phraseIndex||0)?'current':''}" onclick="state.phraseIndex=${i};render()"><b>${x[0]}</b><span>${x[1]}</span><small>${x[2]}</small><i>›</i></button>`).join('')}</div></div>`}
function quizPage(){let qi=state.quizIndex||0,q=quiz[qi%quiz.length];return `${topbar('Anime Knowledge','A playful quiz for curious fans — never an IQ test.') }<div class="quiz-wrap"><div class="quiz-top"><span class="pill violet">QUESTION ${(qi%quiz.length)+1} OF ${quiz.length}</span><span class="subtle">${q[4]} · ${q[3]}</span></div><div class="quiz-card"><div class="quiz-mark">?</div><h2>${q[0]}</h2><div class="answers">${q[1].map((a,i)=>`<button onclick="answerQuiz(${i},${q[2]})"><span>${String.fromCharCode(65+i)}</span>${a}</button>`).join('')}</div></div><div class="quiz-progress"><i style="width:${((qi%quiz.length)/quiz.length)*100}%"></i></div><p class="center subtle">Your score: ${state.quizScore||0} correct · ${state.quizAnswered||0} answered</p></div>`}
function games(){return `${topbar('Game Center','A few cozy ways to play between episodes.') }<div class="game-grid"><div class="game-card tic"><span>✦</span><h2>Tic-Tac-Toe</h2><p>Challenge a friendly opponent in three rows.</p><button class="primary" onclick="startGame()">Play now →</button></div><div class="game-card emoji"><span>◉</span><h2>Anime Emoji Puzzle</h2><p>Can you decode the title from three clues?</p><button class="outline" onclick="emojiGame()">Start puzzle</button></div><div class="game-card guess"><span>?</span><h2>Anime Guess</h2><p>Test your instincts with a title clue.</p><button class="outline" onclick="guessGame()">Take a guess</button></div></div><div id="game-board"></div>`}
function match(){return `${topbar('Who Is Your Anime Match?','A playful, transparent match for fictional fun — not a compatibility test.') }<div class="match-shell"><div class="match-art"><div class="match-orbit"></div><div class="match-heart">♡</div></div><div class="match-copy"><span class="pill pink">JUST FOR FUN</span><h2>Find your fictional match.</h2><p>Answer a few playful questions about the personalities and stories you gravitate toward. We’ll show our reasoning, not a scientific verdict.</p><div class="match-questions"><label>What personality attracts you?<select id="m1"><option>Kind and thoughtful</option><option>Brave and bold</option><option>Mysterious and clever</option><option>Funny and chaotic</option></select></label><label>How do you react under pressure?<select id="m2"><option>Plan carefully</option><option>Jump into action</option><option>Look for a creative way out</option><option>Keep everyone laughing</option></select></label></div><button class="primary" onclick="revealMatch()">Reveal my match ✦</button></div></div>`}
function settings(){return `${topbar('Settings','Make Anime Partner feel like yours.') }<div class="settings-layout"><div class="settings-nav"><button class="active">Preferences</button><button onclick="toast('Privacy center is local-only by design.')">Privacy & data</button><button onclick="window.open('https://docs.google.com/forms/d/e/1FAIpQLSeCRv-8h6WnD4uDQkqVctEWXKNuYSdqnr4l89IzxL7doHa2cw/viewform?usp=publish-editor','_blank')">Feedback & review</button><button onclick="window.open('https://www.instagram.com/shin.ali96/','_blank')">Developer</button></div><div class="settings-panel"><section><h2>Appearance</h2><div class="setting-row"><div><b>Theme</b><small>Choose how Anime Partner looks</small></div><select onchange="state.settings.theme=this.value;save();render()"><option ${state.settings.theme==='dark'?'selected':''}>dark</option><option ${state.settings.theme==='light'?'selected':''}>light</option></select></div><div class="setting-row"><div><b>Reduce motion</b><small>Keep transitions gentle</small></div><input type="checkbox" ${!state.settings.motion?'checked':''} onchange="state.settings.motion=!this.checked;save();render()"></div><div class="setting-row"><div><b>In-app notifications</b><small>Occasional helpful reminders</small></div><input type="checkbox" ${state.settings.notifications?'checked':''} onchange="state.settings.notifications=this.checked;save()"></div></section><section><h2>Profile</h2><div class="profile-block"><span class="avatar big">${initials(state.profile.name||'Y')}</span><div><h3>${esc(state.profile.name||'Your profile')}</h3><p>${state.profile.age?`${state.profile.age} years old · `:''}${state.profile.experience||'Anime explorer'}</p></div><button class="outline" onclick="resetOnboarding()">Edit profile</button></div></section><section><h2>Data & privacy</h2><p class="subtle">Your profile, preferences, notes and progress stay in this browser. Anime Partner does not require an account or collect unnecessary personal information.</p><div class="button-row"><button class="outline" onclick="exportData()">Export my data</button><button class="danger" onclick="clearData()">Clear local data</button></div></section><section><h2>About</h2><p class="subtle">Anime Partner · v1.0<br>Developed by Shin · Offline-first companion for anime fans.</p><div class="button-row"><button class="textbtn" onclick="toast('Terms and Privacy are designed for an offline-first app. Review before release.')">Terms & Privacy</button><button class="textbtn" onclick="window.open('https://www.instagram.com/shin.ali96/','_blank')">Follow developer ↗</button></div></section></div></div>`}
function searchPage(){return discover()}
function empty(title,text){return `<div class="empty"><div>◌</div><h3>${title}</h3><p>${text}</p><button class="outline" onclick="go('discover')">Explore anime</button></div>`}
function onboarding(){let step=state.onboardStep||0; if(step===3)return `<div class="onboard simple"><div class="onboard-card taste-card"><span class="step">YOUR TASTE PROFILE · 04</span><h1>What sounds like<br><em>your kind of story?</em></h1><p>Pick as many as you like. This is an entertainment profile, not a diagnosis.</p><div class="taste-grid">${onboardingQuestions.map((q,i)=>`<button class="taste-option ${state.answers.includes(q)?'selected':''}" data-value="${q}" onclick="toggleTaste(this)">${q}</button>`).join('')}</div><button class="primary full" onclick="finishTaste()">Build my recommendations ✦</button></div></div>`; if(step===0)return `<div class="onboard"><div class="onboard-art"><div class="hero-spark">✦</div><div class="onboard-orbit"></div><div class="onboard-title">ANIME<br><em>PARTNER</em></div><p>Watch Anime With Your Partner</p></div><div class="onboard-card"><span class="step">WELCOME · 01</span><h1>Your next favorite<br><em>is waiting.</em></h1><p>A thoughtful anime companion for discovery, tracking, learning and a little fun.</p><div class="legal"><b>Before we begin</b><p>Anime Partner works offline and saves your choices locally on this device. No account is required.</p><label><input type="checkbox" id="agree" onchange="document.querySelector('#continue').disabled=!this.checked"> I agree to the <u>Terms & Conditions</u> and <u>Privacy Policy</u>.</label></div><button id="continue" class="primary full" disabled onclick="state.onboardStep=1;save();render()">Continue <span>→</span></button></div></div>`; if(step===1)return `<div class="onboard simple"><div class="onboard-card"><span class="step">YOUR PROFILE · 02</span><h1>Let’s get<br><em>personal.</em></h1><p>Just a few basics. Nothing unnecessary, and everything stays on this device.</p><label class="field">What should we call you?<input id="pname" placeholder="Your name" value="${esc(state.profile.name)}"></label><label class="field">How old are you?<input id="page" type="number" min="13" max="120" placeholder="13+" value="${state.profile.age}"></label><label class="field">How do you identify? <select id="pgender"><option value="">Prefer not to say</option><option>Woman</option><option>Man</option><option>Non-binary</option></select></label><button class="primary full" onclick="profileNext()">Continue <span>→</span></button></div></div>`;return `<div class="onboard simple"><div class="onboard-card"><span class="step">YOUR TASTE · 03</span><h1>What’s your anime<br><em>experience?</em></h1><p>This helps us make your first recommendations feel right.</p><div class="experience"><button onclick="finishOnboard('Beginner')"><b>🌱 Beginner</b><small>I’m discovering anime and want a guided start.</small></button><button onclick="finishOnboard('Experienced')"><b>✦ Experienced</b><small>I know what I like and want deeper picks.</small></button></div></div></div>`}
function profileNext(){let age=+document.querySelector('#page').value;if(!document.querySelector('#pname').value.trim()||age<13||age>120)return toast('Please enter a name and a valid age (13 or older).');state.profile={name:document.querySelector('#pname').value.trim(),age,gender:document.querySelector('#pgender').value,experience:''};state.onboardStep=2;save();render()}
function finishOnboard(exp){state.profile.experience=exp;if(exp==='Beginner'){state.onboardStep=3;save();render();return}state.onboarded=true;state.page='home';save();render();toast(`Welcome, ${state.profile.name}!`)}
function finishTaste(){state.answers=[...document.querySelectorAll('.taste-option.selected')].map(x=>x.dataset.value);state.onboarded=true;state.page='home';save();render();toast('Your taste profile is ready ✦')}
function toggleTaste(el){el.classList.toggle('selected')}
function toggleFav(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render();toast(state.favorites.includes(id)?'Added to favorites':'Removed from favorites')}
function start(id){state.watching[id]=(state.watching[id]||0)||1;save();go('tracker');toast('Added to Currently Watching')}
function episode(id){state.watching[id]=(state.watching[id]||0)+1;state.challenges[0].current++;save();render();toast('Episode complete! Keep going ✦')}
function nextPhrase(){state.phraseIndex=((state.phraseIndex||0)+1)%phrases.length;save();render()}
function speak(txt){if('speechSynthesis' in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(txt);u.lang='ja-JP';speechSynthesis.speak(u)}else toast('Speech synthesis is not supported here.')}
function answerQuiz(i,correct){let good=i===correct;state.quizScore=(state.quizScore||0)+(good?1:0);state.quizAnswered=(state.quizAnswered||0)+1;state.quizIndex=(state.quizIndex||0)+1;save();toast(good?'Correct! ✦':'Not quite — keep exploring.');render()}
function newChallenge(){let title=prompt('What goal would you like to set?','Watch 5 episodes this week');if(title){state.challenges.push({id:Date.now(),title,goal:5,current:0});save();render()}}
function startGame(){document.querySelector('#game-board').innerHTML=`<div class="tic-board"><h2>Friendly Tic-Tac-Toe</h2><div class="board">${Array(9).fill(0).map((_,i)=>`<button onclick="ticMove(this,${i})"></button>`).join('')}</div><p id="tic-status">Your move · You are ✦</p><button class="outline" onclick="startGame()">Reset</button></div>`}
let tic=[];function ticMove(el,i){if(tic[i])return;tic[i]='X';el.textContent='✦';if(checkWin(tic,'X'))return toast('You win! ✦');if(tic.filter(Boolean).length===9)return toast('A thoughtful draw.');let e=[0,1,2,3,4,5,6,7,8].find(x=>!tic[x]);tic[e]='O';document.querySelectorAll('.board button')[e].textContent='○';if(checkWin(tic,'O'))toast('The board wins this round!');}function checkWin(b,x){return [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(c=>c.every(i=>b[i]===x))}
function emojiGame(){toast('🌊 + 👧 + ⏳ = Your Name! Nice one.')}function guessGame(){let a=anime[Math.floor(Math.random()*anime.length)];toast(`Clue: this title is tagged “${a.tag}”. Is it ${a.title}?`)}
function revealMatch(){let ch=state.profile.gender==='Man'?'Violet Evergarden':state.profile.gender==='Woman'?'Loid Forger':'Frieren: Beyond Journey’s End';let a=anime.find(x=>x.title===ch)||anime[0];document.querySelector('.match-shell').innerHTML=`<div class="match-result"><div class="scratch">${poster(a,true)}<span>✦</span></div><div><span class="pill pink">YOUR ANIME PARTNER</span><h2>${esc(ch)}</h2><p class="jp">${a.jp||''}</p><div class="match-score">87% <small>entertainment match</small></div><p>Our playful algorithm noticed your interest in <b>${a.genres.slice(0,2).join(' and ').toLowerCase()}</b> and a preference for characters with a memorable inner world.</p><button class="outline" onclick="go('discover')">Find more like this →</button></div></div>`}
function shareAnime(t){navigator.clipboard?.writeText(`${t} — discovered with Anime Partner`);toast('Copied a share message')}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='anime-partner-data.json';a.click()}
function clearData(){if(confirm('Clear all local Anime Partner data?')){localStorage.removeItem(KEY);location.reload()}}
function resetOnboarding(){state.onboarded=false;state.onboardStep=1;save();render()}
function render(){document.documentElement.dataset.theme=state.settings.theme;document.documentElement.classList.toggle('reduced',!state.settings.motion);if(!state.onboarded){app.innerHTML=onboarding();return}if(state.detail){let a=find(state.detail);app.innerHTML=`<div class="layout">${nav()}<main>${detailPage(a)}</main></div>`;return}let content={home,discover,tracker,learn,quiz:quizPage,games,match,settings,search:searchPage}[state.page]||home;app.innerHTML=`<div class="layout">${nav()}<main>${content()}</main></div>`}
Object.assign(window,{state,save,render,go,detail,toggleFav,start,episode,nextPhrase,speak,answerQuiz,newChallenge,startGame,ticMove,emojiGame,guessGame,revealMatch,shareAnime,exportData,clearData,resetOnboarding,profileNext,finishOnboard,finishTaste,toggleTaste});
render();
